\connect onlinestore;

INSERT INTO banks (bank_id, name, is_delete, is_active, created_at, updated_at)
VALUES
(1, 'Mellat', FALSE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Saderat Iran', FALSE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Tejarat', FALSE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'Maskan', FALSE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'Keshavarzi', FALSE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Sepah', FALSE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'Parsian', FALSE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 'Pasargad', FALSE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 'Saman', FALSE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 'Eghtesad Novin', FALSE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 'Shahr', FALSE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 'Melli Iran', FALSE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (bank_id) DO NOTHING;